### ISSUE TITLE
API docs not showing in nix (development + production) environment

### ISSUE THREAD

**Issue by sloschert** [ida-arbeitszeit/workers-control#712]
Since merge of commit b5a6cdb551f4a5d28f92577df8bdb1032f0b2b4e in Pull Request #708 the API documentation is not showing on route `/api/v1/doc/`.

Steps to reproduce:
----------------------------
Visit a live app, e.g. app.arbeitszeitrechnung.org OR activate the nix development environment and visit the development instance on `/api/v1/doc/`.

Instead of the documentation there is a blank page. Errors:

```bash
127.0.0.1 - - [07/May/2023 19:31:15] "GET /api/v1/doc/ HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2023 19:31:15] "GET /swaggerui/droid-sans.css HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2023 19:31:15] "GET /swaggerui/swagger-ui.css HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2023 19:31:15] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2023 19:31:15] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 404 -
```

Possible fix:
-----------------

This problem does not ocurr when in pip environment.  Perhaps there is a problem with the nix package in nixpkgs. We could revert the commit mentioned above and use the custom packaging instructions.

**Comment by seppeljordan** [comment]
I doubt that the problem is with the nix package since the packaging instructions for `flask-restx` in `nixpkgs` is identical to the instructions removed by https://github.com/arbeitszeit/arbeitszeitapp/pull/708/commits/251e0176e0a65c18fe61f3d4a42c8779143ba96f

The version of flask-restx used in `nixpkgs` is `1.1` but the version that we used bevore https://github.com/arbeitszeit/arbeitszeitapp/pull/708/commits/251e0176e0a65c18fe61f3d4a42c8779143ba96f was version `1.0.5`. In the [changelog of `flask-restx`](https://github.com/arbeitszeit/arbeitszeitapp/pull/708/commits/251e0176e0a65c18fe61f3d4a42c8779143ba96f) they specify that the swagger UI was updated. Before reverting the commit I would suggest that we check if updating the manual packaging instructions to use version `1.1` solves the problem.

**Comment by seppeljordan** [comment]
After solving this issue we should have a regression test for this.

**Comment by seppeljordan** [comment]
After investigating a little bit I found that the issue is actually with `nixpkgs`. The version of `flask-restx` distributed by `nixpkgs` is built from source directly downloaded from github. Our custom packaging instructions used the source distribution from PyPI.  The source code of `flask-restx` on github does not provide any web assets (css, js) whereas these assets are included in the source code downloaded from PyPI.

**Comment by seppeljordan** [comment]
The following should do the trick.

```
{ lib, buildPythonPackage, fetchPypi, flask, aniso8601, jsonschema, pytz
, werkzeug }:

buildPythonPackage rec {
  pname = "flask-restx";
  version = "1.1.0";
  format = "setuptools";

  src = fetchPypi {
    inherit pname version;
    sha256 = "sha256-Yra2yd5l5ZYM9PizXhvT7KaZiDigGy9x4qnUwUpMzRQ=";
  };

  propagatedBuildInputs = [ flask aniso8601 jsonschema pytz werkzeug ];

  doCheck = false;

}
```

**Comment by seppeljordan** [comment]
https://github.com/arbeitszeit/arbeitszeitapp/commit/b5a6cdb551f4a5d28f92577df8bdb1032f0b2b4e needs to be reverted though.
