### ISSUE TITLE
RFC: Remove product availability information from the app

### ISSUE THREAD

**Issue by seppeljordan** [ida-arbeitszeit/workers-control#934]
Currently the app allows planners to mark plans as "product available" or "product unavailable" in the UI of the app. I propose to remove this functionality as this feature is not in the domain of labor time accounting. This feature was introduced under the assumption that this might be useful to future users of the app. I have doubts that this will turn out to be since this information will more likely be maintained in the distribution system for goods and services. Since we don't want to build a distribution system we would force all users of the app to maintain this information in the arbeitszeitapp as well.

The above argument lays out why I find the feature not useful, which is not sufficient for removing it.

I say we remove this feature from the app as it increases the work needed for integrating new features. All features that we integrated into the arbeitszeitapp need to deal with the fact that some plans might be marked as "not available". I feel like in the past we often forgot to think about this feature. IMO it would be necessary to go over all the features already in the app and check if we need to add additional logic so that products marked as "not available" are accounted for. We could avoid that by throwing out the feature in question. Also the DB logic could be simplified, columns and filtering methods could be removed.

EDIT: Here are some screenshots for illustration purposes.

![Screenshot from 2024-02-01 14-22-16](https://github.com/arbeitszeit/arbeitszeitapp/assets/4805746/ceda5842-f338-4e2e-9738-18fe1bfd829b)
![Screenshot from 2024-02-01 14-21-45](https://github.com/arbeitszeit/arbeitszeitapp/assets/4805746/1e662305-69e8-40e8-b47f-a99c7655b986)

**Comment by sloschert** [comment]
Thanks for the initiative, @seppeljordan. I agree with your reasoning and to kick this feature out. 

When the development started, the boundaries of arbeitszeitapp as a labour time accounting system were less clear. Two examples: We used to call the plan query page "market place" and thought about having some kind of chat in order to facilitate consumer/producer comunication. Only in such a broad understanding of the arbeitszeitapp as being also a distributing system or market place it would make sense to have such an "availability" marker.

@rhklee: The general idea was to enable for a planning company to mark that, even though there is an active plan in the app, the product of that plan was at the moment unavailable for consumption. I think it is currently just an information for other users, it does not actually prevent anyone from registering consumption of that product.

**Comment by Amittai-Aviram** [comment]
@seppeljordan Jordi, yeah, I (of course) tend to agree with you — this is a matter of clarifying the logic of the current app.  It does raise the question, to my mind, of whether there will, or should, be some other app devoted to distribution.  How would the distribution and labor time accounting apps be coordinated to maintain the general ledger?  This becomes a pretty big question, no?

**Comment by sloschert** [comment]
> How would the distribution and labor time accounting apps be coordinated to maintain the general ledger

@Amittai-Aviram Some important economic considerations on distribution and consumer cooperatives can be found in chapter 7 of the Fundamental Principles,  "The Communist Mode of Distribution" (https://www.marxists.org/subject/left-wing/gik/1930/07.htm).
